'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HappyLand.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EasyAntiCheat() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EasyAntiCheat", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property easyanticheat_wow64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("easyanticheat_wow64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property easyanticheat_wow64_eac() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("easyanticheat_wow64_eac", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EasyAntiCheatsys() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EasyAntiCheatsys", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Info] Desktop screen settings detected. DPI: 96 DPI Multiplier: 1.000000 BPP: 32.
        '''[Info] Localization loaded for: &apos;th-TH&apos;.
        '''[Info] Settings file full path: &apos;C:\Program Files (x86)\Gravity Game Tech\RagnarokOnline - 07.08.63\RagnarokOnline - 07.08.63\EasyAntiCheat\Launcher\Settings.json&apos;.
        '''[Info] Start. ExecutablePath: &apos;C:\Program Files (x86)\Gravity Game Tech\RagnarokOnline - 07.08.63\RagnarokOnline - 07.08.63\/Ragexe.exe&apos; LaunchParameters: &apos;/Ragexe.exe&apos; LaunchParameters: &apos;1rag1 -eac_executablename &quot;Ragex [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property gamelauncher() As String
            Get
                Return ResourceManager.GetString("gamelauncher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [2020.08.12-23.32.00] Loader initialized.
        '''[2020.08.12-23.32.00] [Connection] Connecting to URL: https://download.eac-cdn.com/api/v1/games/525/client/wow64/download/?uuid=4a56a076-4a8d-b8ac-7cdd-fdff6880a7b2
        '''[2020.08.12-23.32.00] Download Progress: 0%.
        '''[2020.08.12-23.32.00] Download Progress: 0%.
        '''[2020.08.12-23.32.00] Download Progress: 0%.
        '''[2020.08.12-23.32.00] Download Progress: 0%.
        '''[2020.08.12-23.32.00] Download Progress: 0%.
        '''[2020.08.12-23.32.00] Download Progress: 0%.
        '''[2020.08.12-23.32.00] Downl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property loader() As String
            Get
                Return ResourceManager.GetString("loader", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
